server:
  port: 7070

my:
  upload_dir: ${my.upload_dir}
  password: ${my.password}

spring:
#  main:
#    allow-bean-definition-overriding: true
  datasource:
#    url: ${db.url}
    url: jdbc:mysql://localhost:3306/xw_admin(rbac)?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=true
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: localhost
    port: 6379
    password:


#  application:
#    # 微服务名称，供别人调用
#    name: xw01-user
  cloud:
#    nacos:
#      server-addr: 127.0.0.1:8848
#      username: nacos
#      password: nacos
    sentinel:
      eager: true  # 取消懒加载
      transport:
        dashboard: localhost:8480 # 配置Sentinel dashboard地址
feign:
  sentinel:
    enabled: true








mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      db-type: mysql
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

seata:
  registry: #如何与seata服务器通讯s
    type: nacos
    nacos:
      namespace:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      userName: "nacos"
      password: "nacos"
  config:  #如何读取配置中心关于client的配置
    type: nacos
    nacos:
      namespace:
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      userName: "nacos"
      password: "nacos"
      data-id: seataServer.properties
  tx-service-group: guangzhou